### ISSUE TITLE
Sprint 2 Planning To-Do List 04/26/2021

### ISSUE THREAD

**Issue by Dantzzz** [Dantzzz/MuckScraper#4]
Refer to Planning board...
- [ ] "Correct DateTime nullable issue with JSON return in ArticleJson class." https://github.com/users/Dantzzz/projects/1#card-59860078
- [ ] "Merge first and last name fields into one field." https://github.com/users/Dantzzz/projects/1#card-59860185 
- [ ] "Remove front-end access to fields, excluding SourceUrl." https://github.com/users/Dantzzz/projects/1#card-59860362
- [ ] "Write methods to store article plain text inside object." https://github.com/users/Dantzzz/projects/1#card-59409164
- [ ] "Write method to parse article information from API JSON in order to automate populating the object's fields." https://github.com/users/Dantzzz/projects/1#card-59409243
